config/routes.rb
Items::Application.routes.draw do
  resources :t_formats

  resources :formats

  resources :relations

  resources :items

  get "pages/tables"

  get "pages/about"

end

app/models/relation.rb
class Relation < ActiveRecord::Base
  belongs_to :type
  belongs_to :parent, :class_name => "Item"
  belongs_to :child,   :class_name => "Item"
end

app/controllers/relations_controller.rb
class RelationsController < ApplicationController
  before_action :set_relation, only: [:show, :edit, :update, :destroy]

  # GET /relations
  # GET /relations.json
  def index
    @relations = Relation.all
  end

  # GET /relations/1
  # GET /relations/1.json
  def show
  end

  # GET /relations/new
  def new
    @relation = Relation.new
  end

  # GET /relations/1/edit
  def edit
  end

  # POST /relations
  # POST /relations.json
  def create
    @relation = Relation.new(relation_params)

    respond_to do |format|
      if @relation.save
        format.html { redirect_to @relation, notice: 'Relation was successfully created.' }
        format.json { render action: 'show', status: :created, location: @relation }
      else
        format.html { render action: 'new' }
        format.json { render json: @relation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /relations/1
  # PATCH/PUT /relations/1.json
  def update
    respond_to do |format|
      if @relation.update(relation_params)
        format.html { redirect_to @relation, notice: 'Relation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @relation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /relations/1
  # DELETE /relations/1.json
  def destroy
    @relation.destroy
    respond_to do |format|
      format.html { redirect_to relations_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_relation
      @relation = Relation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def relation_params
      params.require(:relation).permit(:item_id, :itemable_id, :type_id)
    end
end

app/helpers/relations_helper.rb
module RelationsHelper
end

app/views/relations/_form.html.erb
<%= form_for(@relation) do |f| %>
  <% if @relation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@relation.errors.count, "error") %> prohibited this relation from being saved:</h2>

      <ul>
      <% @relation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :item_id %><br>
    <%= f.number_field :item_id %>
  </div>
  <div class="field">
    <%= f.label :itemable_id %><br>
    <%= f.number_field :itemable_id %>
  </div>
  <div class="field">
    <%= f.label :type_id %><br>
    <%= f.number_field :type_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/relations/edit.html.erb
<h1>Editing relation</h1>

<%= render 'form' %>

<%= link_to 'Show', @relation %> |
<%= link_to 'Back', relations_path %>

app/views/relations/index.html.erb
<h1>Listing relations</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th>Parent</th>
      <th>Child</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @relations.each do |relation| %>
      <tr>
        <td><%= relation.name %></td>
        <td><%= relation.type.name %></td>
        <td><%= relation.parent.name %></td>
        <td><%= relation.child.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Relation', new_relation_path %>

app/views/relations/new.html.erb
<h1>New relation</h1>

<%= render 'form' %>

<%= link_to 'Back', relations_path %>

app/views/relations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Item:</strong>
  <%= @relation.item_id %>
</p>

<p>
  <strong>Itemable:</strong>
  <%= @relation.itemable_id %>
</p>

<p>
  <strong>Type:</strong>
  <%= @relation.type_id %>
</p>

<%= link_to 'Edit', edit_relation_path(@relation) %> |
<%= link_to 'Back', relations_path %>