config/routes.rb
Items::Application.routes.draw do
  resources :t_formats

  resources :formats

  resources :relations

  resources :items

  get "pages/tables"

  get "pages/about"

end

app/views/pages/about.html.erb
<h1>About TOM</h1>
<p>Technical Officer's Management</p>

<div id="tabs">
  <ul>
    <li><a href="#tabs-1">Overview</a></li>
    <li><a href="#tabs-2">Features</a></li>
    <li><a href="#tabs-3">Comments</a></li>
    <li><a href="#tabs-4">Screenshots</a></li>
  </ul>
  <div id="tabs-1">Overview Page</div>
  <div id="tabs-2">Features Page</div>
  <div id="tabs-3">Comments Page</div>
  <div id="tabs-4">Screenshots Page</div>
</div>



<a href='javascript: toggle()'>toggle</a>
<div id='div1' style='display:none'>
Don't display me
</div>

<script>
function toggle(){
	var div1 = document.getElementById('div1')
	if (div1.style.display == 'none') {
		div1.style.display = 'block'
	} else {
		div1.style.display = 'none'
	}
}
</script>

<style type="text/css" media="screen">
#countdown-wrapper {
	margin-left: auto;
	margin-right: auto;
	text-align: center;
	width: 515px;
}
#countdown {
	text-align: left;
	width: 515px;
}
#timer-title {
	margin-bottom:20px;
}
.counter-block {
	background-image: -webkit-gradient(
		linear,
		left bottom,
		left top,
		color-stop(0.04,rgb(0,0,0)),
		color-stop(0.52,rgb(54,54,54)),
		color-stop(0.76,rgb(82,82,82))
		);
	background-image: -moz-linear-gradient(
		center bottom,
		rgb(0,0,0) 4%,
		rgb(54,54,54) 52%,
		rgb(82,82,82) 76%
		);
	background-color:black;
		-webkit-border-radius:8px;
	-moz-border-radius: 8px;
	border-radius: 8px;
	font-size: 46px;
	color: #FFF;
	height: 90px;
	width: 120px;
	margin: 0 6px 0 0;
	float: left;
	font-family: helvetica,arial,sans-serif;
	font-weight: bold;
	border: 1px solid #000000;
	padding: 0;
	line-height: 48px;
	text-shadow: #000000 1px 1px 2px;}
.counter-block-inner {
	line-height: 48px;
	padding: 0;
	text-align: center;
	margin-top: 20px;
}
.counter-block-type {
	color: #666666;
	font-size: 24px;
	margin-left: -8px;
}
.expired {
	text-align: center;
}

</style>
<div id="countdown-wrapper">
		<h3 id="timer-title"></h3>
		<div id="countdown"></div>
</div>
<br style="clear:both;" />
<script type="text/javascript" charset="utf-8">
var passedDate = "11/30/2011 11:00";
var expireMessage = "";
eval(function(p,a,c,k,e,r){e=function(c){return(c<a?'':e(parseInt(c/a)))+((c=c%a)>35?String.fromCharCode(c+29):c.toString(36))};if(!''.replace(/^/,String)){while(c--)r[e(c)]=k[c]||e(c);k=[function(e){return r[e]}];e=function(){return'\\w+'};c=1};while(c--)if(k[c])p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c]);return p}('u(E);j u(v){c w=k l(k l(v)-k l());c x=y.z(w.F()/G);n("e",x)}j b(8,A,B){s=((y.z(8/A))%B).I();C(s.J<2){s="0"+s}K(s)}j n(L,8){c 3;c o="<4 5=\'6-7\'><4 5=\'6-7-f\'>%%D%% <9 5=\'6-7-i\'>d</9></4></4> <4 5=\'6-7\'><4 5=\'6-7-f\'>%%H%% <9 5=\'6-7-i\'>h</9></4></4> <4 5=\'6-7\'><4 5=\'6-7-f\'>%%M%% <9 5=\'6-7-i\'>m</9></4></4> <4 5=\'6-7\'><4 5=\'6-7-f\'>%%S%% <9 5=\'6-7-i\'>s</9></4></4>";3=o.a(/%%D%%/g,b(8,N,O));3=3.a(/%%H%%/g,b(8,P,Q));3=3.a(/%%M%%/g,b(8,p,p));3=3.a(/%%S%%/g,b(8,1,p));C(8>0){q.r("e").t=3;R("n(\'"+"e"+"\',"+(8-1)+");",T)}U{3=o.a(/%%D%%/g,0);3=3.a(/%%H%%/g,0);3=3.a(/%%M%%/g,0);3=3.a(/%%S%%/g,0);q.r("e").t=3;q.r("V-W").t=X}}',60,60,'|||CountDown|div|class|counter|block|seconds|span|replace|RunCounter|var||countdown|inner|||type|function|new|Date||BackTick|CounterFormat|60|document|getElementById||innerHTML|StartCount|SelectedDateTime|startVsEnd|diffseconds|Math|floor|first|second|if||passedDate|valueOf|1000||toString|length|return|counterDiv||86400|100000|3600|24|setTimeout||990|else|timer|title|expireMessage'.split('|'),0,{}))</script>


http://www.skyrocketclock.com/premier/

app/views/pages/tables.html.erb
<h1>Table Overview</h1>

<ul>
<li> <%= link_to "Items", items_path =%>
<li> <%= link_to "Formats", formats_path =%>
<li> <%= link_to "Relations", relations_path =%>
</ul>